---
title: "Motion_CM_Analysis"
author: "Yiren"
date: "12/8/2019"
output: html_document
---

#Header1
Analysis

```{r libraries }
library(ggplot2)
library(rstudioapi)
library(plyr)

library(dplyr)
```


#set directory

cm analysis
load flattened data

```{r load_data}
#set directory and load data
df <- read.table(file = "motion_cm_pilot1.tsv", sep = '\t',header = TRUE)
head(df)
```

# check flattened data

```{r}
head(df$realPercentage,5)
df <- df %>% mutate(diff= abs(realPercentage*100-selectedPercentage))
df <- df %>% mutate(diffraw= selectedPercentage-realPercentage*100)

head(df$diff,5)
df <- df %>% mutate(err= log(diff+0.125,2))
df
```

# cal summary
```{r}
conf_level= 0.95
summary <- ddply(df, c("vis","realPercentage"), summarise,
                 N    = length(err),
                 mean = mean(err),
                 sd   = sd(err),
                 se   = sd / sqrt(N),
                 ci  = mean - qt(1 - ((1 - conf_level) / 2), N - 1) * se
)
summary
#cm error
summary <- summary %>% mutate(err= log(mean+0.125,2))
```

#plot Line chart for both

```{r}
ggplot(summary, aes(x=realPercentage, y=mean, group=vis)) +
  geom_line(aes(color=vis))+
  geom_point(aes(color=vis))+
  theme(legend.position="top")

movingSummary <- subset(summary,  vis== "moving")
rotationSummary <- subset(summary,  vis== "rotation")
```

#moving ci plot

```{r}
ggplot(movingSummary, aes(x=realPercentage, y=mean )) +
  geom_line(aes(color=vis))+
  geom_point(aes(color=vis, size =1))+
  geom_errorbar(aes(ymin=mean-ci, ymax=mean+ci), colour="black", width=.03) +
  theme(legend.position="top")
```


#rotation ci plot

```{r}
ggplot(rotationSummary, aes(x=realPercentage, y=mean )) +
  geom_line(aes(color=vis))+
  geom_point(aes(color=vis, size =3))+
  geom_errorbar(aes(ymin=mean-ci, ymax=mean+ci), colour="black", width=.03) +
  theme(legend.position="top")
```

#ci sum

```{r}
summaryAll <- ddply(df, c("vis"), summarise,
                    N    = length(err),
                    mean = mean(err),
                    sd   = sd(err),
                    se   = sd / sqrt(N),
                    ci  = mean - qt(1 - ((1 - conf_level) / 2), N - 1) * se
)
summaryAll
```


#Plot overall CI

```{r}
ggplot(summaryAll, aes(x=vis, y=mean)) +
  geom_point(aes(color=vis, size =3))+
  geom_errorbar(aes(ymin=mean-ci, ymax=mean+ci), colour="black", width=.03) +
  theme(legend.position="top")
```

#Scatter plot of data

```{r}
ggplot(df, aes(x=vis, y=diffraw,group =vis)) +
  geom_point(aes(color=vis))+
  theme(legend.position="top")
```

#Interactive Test

```{r}
# Define the content and format of the tooltip in the "text" aesthetic
df
# Define the content and format of the tooltip in the "text" aesthetic
p <- ggplot(df, aes(x=vis, y=diffraw, group=vis,
                    text=paste("sessionId:",sessionId,"time:",trialEndTime/1000-trialStartTime/1000))) + 
  geom_point(aes(color=vis))+
  facet_wrap(~sessionId)

library(plotly)
p <- ggplotly(p, tooltip="text")
print(p)
```









